### ISSUE TITLE
Expand `gear-program` functionality

### ISSUE THREAD

**Issue by breathx** [gear-tech/gear#1006]
### Problem to Solve

Provide new features

### Possible Solution

** To be pasted from ecosystem requirements **

**Comment by shamilsan** [comment]
Should we add such issues to the https://github.com/gear-tech/gear-program repo, aren't we?

**Comment by breathx** [comment]
> Should we add such issues to the https://github.com/gear-tech/gear-program repo, aren't we?

🧐 Forgot about such possibility, sorry
You are totally right. We need to beautify that repo, create CI, open issues and cover with docs, also linking it in our wiki!
