### ISSUE TITLE
Clearing storage from "graves"

### ISSUE THREAD

**Issue by breathx** [gear-tech/gear#1014]
### File Location(s)

`gear_common::event`
`pallets/gear-program`

### Proposal

Need to decide should we clear inactive codes and paused programs after some time, e.g. 1 month?

**Comment by gshep** [comment]
relates to #880

**Comment by breathx** [comment]
> relates to #880

I don't actually think so. It's more about outdated paused programs

**Comment by shamilsan** [comment]
We will not remove paused programs (as they don't take up too much space). Code related issue is to be discussed, though.
