### ISSUE TITLE
Roll back program state if submitted WASM produces trap

### ISSUE THREAD

**Issue by Anfid** [gear-tech/gear#108]
### Problem to Solve

Currently program state is saved regardless of execution result. It makes possible following unwanted conditions:
* Allocated memory pages may not be freed upon exit (#80)
* Program may end up in corrupted state

### Possible Solution

Prevent saving program state, outgoing and incoming messages if trap is produced. Another option is to provide default panic handler that would roll back state. Users will be able to opt-out from it and preserve state on trap.

### Notes

Following cases have to be considered:
* Should gas be deduced for unsuccessful executions? If so, how much? If not, could it be a potential DOS vulnerability?
* Program must not loose any incoming messages if state was not preserved. How should infinite loop of handling incoming message and producing a trap be prevented?
* Mechanism to recover from such errors should be present. E.g. updating submitted code with preserved state and/or messages.

**Comment by SabaunT** [comment]
Quick possible solution can be to first discover the execution outcome and only then perform program set to the storage.
