### ISSUE TITLE
Parse received errors in programs

### ISSUE THREAD

**Issue by breathx** [gear-tech/gear#1084]
### Problem to Solve

Once #970 will be resolved, there will be need to parse the received error

### Possible Solution

Once error reply received, downcast in into the core-errors, or wait and follow the solution of #1083 afterwards.

### Notes

Provide this thing for `gcore`, `gstd` and `gtest`

**Comment by clearloop** [comment]
since `gcore` contains custom interfaces for host functions, we need provide a interface to parse the error reply also?

otherwise, for just parsing the error reply, we can just add a function in gstd

```
fn exec::error_reply() -> Result<(), ExtError> {
   if gr_exit_code() != ERR_EXIT_CODE {
      Ok(())
   } else {
      Err(ExtCode::decode(...))
   }
}
```

**Comment by ark0f** [comment]
Proposal: https://gist.github.com/ark0f/c5276d80d184d2a6b2b2ffcb47a6ac65
