### ISSUE TITLE
Extend `gtest::Program::meta_state` functionality and make it fallible

### ISSUE THREAD

**Issue by dustyNdumb** [gear-tech/gear#1089]
### Problem to Solve

For now `meta_state` functions panics if the associated binary wasm function panics in the executor. Also, it gives no error message about its failure

### Possible Solution

`gtest::manager` doesn't panic even if inner execution does. It implements `RunResult` logic that shows if execution failed and stores its error message. We can use that logic in `gtest::wasm_executor`

**Comment by breathx** [comment]
That's not about RunResult
We just need to make reading state fallible
`fn meta_state( ... ) -> Result< ... , trap explanation >`

**Comment by breathx** [comment]
Also we should provide `meta_state` for `WasmProgram` trait!
