### ISSUE TITLE
Change program upload logic in `gtest`

### ISSUE THREAD

**Issue by ukint-vs** [gear-tech/gear#1096]
### File Location(s)

gtest/src/program.rs
gtest/src/manager.rs

### Proposal

Since we reject non-gear exports in `gear_core::code::Code::try_new()` we need to process meta wasm file without using `gear_core::program::Program` and execute it as a regular wasm binary without the core logic.
I see it so the manager has a `meta_binaries: BTreeMap<CodeId, Vec<u8>> ` field and executes it via `wasmtime` with memory from `Program`.

For now we are using `Code::new_raw` which cannot be used for testing purposes.

See https://github.com/gear-tech/gear/pull/1085

**Comment by breathx** [comment]
Need to allow creating programs from `.opt.wasm` and `.meta.wasm` separately, or split it under the hood, if given binary has `.wasm` extension with `wasm-proc`
