### ISSUE TITLE
Optimize wasm execution.

### ISSUE THREAD

**Issue by ukint-vs** [gear-tech/gear#1102]
### File Location(s)

core-backend/sandbox/env.rs
core-processor/src/executor.rs
lazy-pages/src/lib.rs

### Proposal

Due to expensive syscalls, the `demo-async-multisig` does not pass all fixtures, we need to look towards optimizing syscalls or adding the ability to add gas in the case of asynchronous messages.

See https://github.com/gear-tech/gear/pull/1013

**Comment by breathx** [comment]
This may be also solved by appending more gas for messages in runtime spec tests:
https://github.com/gear-tech/gear/blob/0b1090afd6cf368cb23ced6c6896524869632e9a/utils/gear-runtime-test-cli/src/command.rs#L298-L300
We shouldn't process all of the messages within the single block.

**Comment by ukint-vs** [comment]
> This may be also solved by appending more gas for messages in runtime spec tests:
> 
> https://github.com/gear-tech/gear/blob/0b1090afd6cf368cb23ced6c6896524869632e9a/utils/gear-runtime-test-cli/src/command.rs#L298-L300
> 
> 
> We shouldn't process all of the messages within the single block.

But in case with `test-async-multisig` there is only one message so `gas_limit` is `GasPallet::<Runtime>::gas_allowance()`

**Comment by breathx** [comment]
> 



> > This may be also solved by appending more gas for messages in runtime spec tests:
> > https://github.com/gear-tech/gear/blob/0b1090afd6cf368cb23ced6c6896524869632e9a/utils/gear-runtime-test-cli/src/command.rs#L298-L300
> > 
> > We shouldn't process all of the messages within the single block.
> 
> But in case with `test-async-multisig` there is only one message so `gas_limit` is `GasPallet::<Runtime>::gas_allowance()`

Yeah, ok, opened separate issue: #1105 
But isn't the init messages work on the same gas allowance within the block?

**Comment by ukint-vs** [comment]
> > 
> 
> > > This may be also solved by appending more gas for messages in runtime spec tests:
> > > https://github.com/gear-tech/gear/blob/0b1090afd6cf368cb23ced6c6896524869632e9a/utils/gear-runtime-test-cli/src/command.rs#L298-L300
> > > 
> > > We shouldn't process all of the messages within the single block.
> > 
> > 
> > But in case with `test-async-multisig` there is only one message so `gas_limit` is `GasPallet::<Runtime>::gas_allowance()`
> 
> Yeah, ok, opened separate issue: #1105 But isn't the init messages work on the same gas allowance within the block?

No, fixture messages are sent after all programs have been initialized.
