### ISSUE TITLE
Panic on OS errors

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#1165]
### File Location(s)

common/src/lazy_pages.rs

### Proposal

There is several places, where in case error appears - it's bad idea to continue execution. This is because this problems are connected with OS  behaviour:
https://github.com/gear-tech/gear/blob/58dec021232bb251a73ed6551d9bc4e2b245c7ef/common/src/lazy_pages.rs#L154-L158

https://github.com/gear-tech/gear/blob/58dec021232bb251a73ed6551d9bc4e2b245c7ef/common/src/lazy_pages.rs#L53-L58

Because this errors may appear because of OS, we cannot guaranty that the same behaviour will be for other nodes in net (actually the most possible case is that it's problem of one node only). So, if we will continue execution - runtime will generate wrong block and this will lead to errors in consensus (for current node).

So, may be the better way is to panic, we must discuss it here

**Comment by grishasobol** [comment]
@NikVolf, I would like to see your opinion

**Comment by NikVolf** [comment]
Unrecoverable state of the system is panic, of course
