### ISSUE TITLE
Add new node flag

### ISSUE THREAD

**Issue by breathx** [gear-tech/gear#1200]
### Problem to Solve

Often we see error logs when node tries to connect to itself if it is specified in the chain spec as boot node.

### Possible Solution

Add some flag to ignore self in boot nodes or make it default behaviour.

### Notes

```shell
ERROR tokio-runtime-worker sc_network::service: 💔
The bootnode you want to connect provided a different peer ID
than the one you expect: `_ID_` with `_ID_`:
`Dialer { address: "_ADDRESS_", role_override: Dialer }`.
```

**Comment by shamilsan** [comment]
This problem seems to be fixed in Substrate, closing.
