### ISSUE TITLE
State view meta information

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#125]
Like we do return meta information on what input and output of the program is, we can introduce couple of more metas

- `meta_state_type` that will return json-type of the `meta_state`
- `meta_state` that will return scale-encoded payload that should be interpreted as type returned by `meta_state_type` 

To actually run `meta_state`, memory for the program `program.meta.wasm` should be extracted from the current chain.

**Comment by breathx** [comment]
Resolved via #410 and via #423 in `gear` repo and PR-146 from `gear-js` repo ? @NikVolf

**Comment by breathx** [comment]
Yeap, resolved in PRs specified above
