### ISSUE TITLE
Tests are failing on nightly compiler

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#127]
`cargo +nightly test -p tests-btree`

running 3 tests
test tests::binary_available ... ok
test tests::program_can_be_initialized ... FAILED
test tests::simple ... FAILED

failures:

---- tests::program_can_be_initialized stdout ----
thread 'tests::program_can_be_initialized' panicked at 'failed to init program: Error loading program: can't find memory export', tests/btree/src/lib.rs:139:14

---- tests::simple stdout ----
thread 'tests::simple' panicked at 'failed to init program: Error loading program: can't find memory export', /Users/nikolayvolf/git/gear/tests/common/src/lib.rs:26:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    tests::program_can_be_initialized
    tests::simple

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

**Comment by shamilsan** [comment]
Fixed in #266.
