### ISSUE TITLE
Develop economic model to derive on-chain constants from

### ISSUE THREAD

**Issue by ekovalev** [gear-tech/gear#1277]
In order to define currency-related runtime constants (UNITS, DOLLARS, CENTS etc.) in terms of the intrinsic token some preliminary token economy model would be very useful.

This will be way more important once staking is introduced because that one is built upon the notion of inflation etc.

Simply copying constants from Substrate or Polkadot/Kusama doesn't really work, because the latter differ a lot from chain to chain. We need our own model.

Parameters to be set:

- [ ] Decimals precision (preliminary value: 12)
- [ ] Bonding/unbonding period
- [ ] Network prefix
- [ ] Units name
- [ ] Initial tokens cap
- [ ] Initial tokens distribution
- [ ] ...

**Comment by breathx** [comment]
Already done in tokenomic model for Vara runtime
