### ISSUE TITLE
Remove possible panics from re-instrumentation result handling

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#1325]
### Problem to Solve

Current solution provided in #897 and #1324 doesn't give any type-level guarantees that re-instrumentation won't fail.

### Possible Solution

We can invalidate code storage if program's code can't be re-instrumented either by demand (in `process_queue`) or by schedule (in `process_tasks`). Possibly solution can be the following: If program's code can't be re-instrumented, it is marked Terminated, funds are moved to some external origin, code is removed from storage.

**Comment by SabaunT** [comment]
After some discussions with @breathx there are several ideas:
1. Pause failing during instrumentation program. Program is waiting in the pause state for free (because our changes were reasons for it to be unavailable anymore). Program waits until suitable weights occur.
2. Leave program with old gas rules on instrumentation failure, but:
  2.1. If instruction weights increase and program's old weights are lower than the current ones, a special coefficient will be used that charges additional gas for executing message to such program.
  2.2. If instruction weights decreased, no coefficient is used.

**Comment by ark0f** [comment]
Not actual anymore because we already use another gas consumption approach
