### ISSUE TITLE
Lazy pages: support `wasmer` in signal handler for `windows`

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#1377]
### Problem

Found a problem using `wasmer` as sandbox executor, because of signal handlers overlap. Fix it for unix in https://github.com/gear-tech/gear/pull/1376 . We need also to fix it for `windows`.

### Steps

To reproduce you can try to upload contract: examples/wat-examples/wrong_load.wat to your node.

**Comment by ark0f** [comment]
We checked the issue on Windows and failed to reproduce such bug because:
@grishasobol investigated that such problem occurs on ARM because memory bounds checks are based on interrupts. On x86 checks are injected into WASM code.

We don't build binaries for Windows ARM so issue can be closed
