### ISSUE TITLE
Ensure smooth transition from PoA to NPoS in Vara

### ISSUE THREAD

**Issue by ekovalev** [gear-tech/gear#1404]
Currently authorities are set in the genesis block. As of `vara-stage-1` there is no mechanism to add/remove authorities by sending a transaction.

The following features must be supported, and their stability guaranteed as we progree from stage-1 to further stages (eventually, to a full-blown NPoS consensus):
- authorities can be added or removed;
- runtime upgrade that switches the consensus to NPoS must guarantee the former PoA authorities become validators; the balance accumulated by the authorities during PoA stage must be staked.

The features above must be extensively tested to ensure a smooth transition.

**Comment by shamilsan** [comment]
> is there any DDL for this? I'm interested with this but not pretty sure I can complete it really fast

@ekovalev is working on this task as far as I know. @ekovalev may I ask you to self-aasign the task?
