### ISSUE TITLE
Lazy pages signal handler overlaps with another ones during simultaneous tests run

### ISSUE THREAD

**Issue by ark0f** [gear-tech/gear#1444]
### Problem

In file `lazy-pages/src/sys/unix.rs`:
```rust
let error_reg = nix::libc::REG_ERR as usize;
let error_code = (*ucontext).uc_mcontext.gregs[error_reg];
```
`error_code` is sometimes zero during during simultaneous tests run when it's expected to be `0b10`

### Steps

Run `cargo test --package gear-lazy-pages --lib tests::read_write_flag_works` (in #1419)

### Possible Solution

- Run tests in 1 thread
- Run tests with signal handler separately

### Notes

| Machine| Kernel | CPU | VM | Works? | Notes |
| --- | --- | --- | --- | --- | --- |
| EPYC CI | 5.15.0-25-generic | AMD EPYC 7502P (64) @ 2.500GHz | ✔️ | ❌ | https://github.com/gear-tech/gear/runs/8208657278?check_suite_focus=true#step:22:754. |
| EPYC CI | 5.15.0-25-generic | AMD EPYC 7502P (64) @ 2.500GHz | ✔️ | ✔️ | `docker run -it ubuntu` |
| EPYC CI | 5.15.0-25-generic | AMD EPYC 7502P (64) @ 2.500GHz | ✔️ | ❌ | `docker run -it ubuntu` with simultaneously tests |
| EPYC CI | 5.15.0-25-generic | AMD EPYC 7502P (64) @ 2.500GHz | ❌ | ✔️ | Linux environment |
| Xeon CI | 5.4.0-122-generic | Intel Xeon E5-2695 v3 (28) @ 3.300GHz | ✔️ | ✔️ | `docker run -it ubuntu` |
| Xeon CI | 5.4.0-122-generic | Intel Xeon E5-2695 v3 (28) @ 3.300GHz | ❌ | ✔️ | Linux environment |
| @ark0f's machine | 4.4.0-19041-Microsoft | AMD Ryzen 5 3600 (12) @ 3.600GHz | ✔️ | ❌ | WSL1 (possibly bad implementation) |
| @ark0f's machine | 5.10.16.3-microsoft-standard-WSL2 | AMD Ryzen 5 3600 (12) @ 3.600GHz | ✔️ | ✔️ | WSL2 |
| @ark0f's machine | 5.18.17 | AMD Ryzen 5 3600 (12) @ 3.600GHz | ❌ | ✔️ | Fedora |
| @ark0f's machine | 5.17.5-300.fc36.x86_64 | AMD Ryzen 5 3600 (12) @ 3.600GHz | ✔️ | ✔️ | VMware Workstation 16 Player for Windows (guest OS is Fedora) |

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
running 1 test
thread 'tests::read_write_flag_works' panicked at 'assertion failed: `(left == right)`
  left: `Some(false)`,
 right: `Some(true)`', lazy-pages/src/lib.rs:339:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tests::read_write_flag_works ... FAILED

failures:

failures:
    tests::read_write_flag_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

</p>
</details>

**Comment by ukint-vs** [comment]
I think it has to do with virtualization. Github runners run inside docker containers. The test passes successfully in the EPYC CI linux environment.

**Comment by ark0f** [comment]
After various runs I found out signal handler just overlaps with another ones
