### ISSUE TITLE
Implement all `pallet_gear` extrinsics generation and test 

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#1449]
Preferably after #1448. That requires implementing:

MVP
- [x] #1601

Phase 2: 
- [ ] send_reply
- [ ] claim_value

Note: these extrinsics require some additional context to be introduced during tests generation.

**Comment by r3bu1ld3r** [comment]
I'll implement test for `upload_code` extrinsic

**Comment by SabaunT** [comment]
After #1498 will work on "send_message"

**Comment by SabaunT** [comment]
> MVP introduced, issue solved by #1588

Not solved yet. Two calls are rest.
