### ISSUE TITLE
checkProcessed does not update processed messages

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#1462]
### Problem

checkProcessed does not update processedMessages storage after first message, so we cannot use it more then once.
https://github.com/gear-tech/gear/blob/bf334b0ddf3ce2ed03b16333603a99eefaf63e59/scripts/test-utils/util.js#L31-L45

### Steps

1. cargo build -p gear-node --release
2. make wat-examples
3. ./scripts/gear.sh test uploads ./target/wat-examples/wrong_load.wasm ./target/wat-examples/wrong_load.wasm

**Comment by breathx** [comment]
Not actual since `gclient` introduced
