### ISSUE TITLE
Rework memory management

### ISSUE THREAD

**Issue by ukint-vs** [gear-tech/gear#15]
Use isolated heap memory instead of shared memory.
This change will transfer the memory limit (4GB) from the entire runtime to a separate program, also allowing parallelism to be used in the future.
The state of the memory heap must be preserved as well as static memory and must be accessible from other programs via API.

- [x] Heap memory management. (89d9952c3fee903984be6f65feb100310ebc74d8)
- [x] Use one memory for each program. (#41)
- [ ] Implement memory access API.

**Comment by shamilsan** [comment]
> The state of the memory ... must be accessible from other programs via API.

Do we still need to have this feature?

**Comment by ukint-vs** [comment]
> > The state of the memory ... must be accessible from other programs via API.
> 
> Do we still need to have this feature?

I think we don't need it anymore.
