### ISSUE TITLE
Add additional checks to the `try-runtime` tool

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#1567]
### Problem to Solve

We need to have a tool that verifies the new runtime before its upgrade.

### Possible Solution

Need to add all possible checks to the `pre_upgrade` and `post_upgrade` hooks.

- [ ] Balances integrity
- [ ] Message queue integrity

### Notes

https://docs.substrate.io/reference/how-to-guides/tools/use-try-runtime/

**Comment by breathx** [comment]
Closing in favour of more complex #2303
