### ISSUE TITLE
Add Vara to SS58 registry and polkadot.js apps config

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#1571]
Need to choose:

- [x] Prefix: `137`
- [x] Network: `"vara"`
- [x] Display Name: `"Vara Network"`
- [x] Symbols: `["VARA"]`
- [x] Decimals: `[12]`
- [x] Standard Account: `"*25519"`
- [x] Website: `"https://vara-network.io"`

Then need to add a PR to the SS58 registry repo: https://github.com/paritytech/ss58-registry

- [ ] Also, need to add a spec to polkadot.js apps config: https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/api/spec

**Comment by shamilsan** [comment]
> https://github.com/polkadot-js/apps/tree/master/packages/apps-config/src/api/spec here also?

Good advice!

**Comment by breathx** [comment]
Fixed [here](https://github.com/paritytech/ss58-registry/pull/135)

**Comment by breathx** [comment]
@EugenWay, could you, please, provide spec to polka js apps also, that mentioned in the issue?

**Comment by EugenWay** [comment]
Yes, it's already done. But for proposing the PR we wait for Vara official announcement, no?

**Comment by shamilsan** [comment]
Done.
https://github.com/polkadot-js/apps/pull/8285
https://github.com/polkadot-js/apps/pull/8285
