### ISSUE TITLE
Fix chain metadata generation in windows

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#1629]
### Problem

https://github.com/gear-tech/gear/actions/runs/3193353703/jobs/5219458435#step:22:3917

### Steps

got this issue from the CI, mb just have problems on WIN, will trigger rebuilding afterwards anyway

### Possible Solution

upgrade `subxt` to `0.24.0`

https://github.com/paritytech/subxt/pull/587

**Comment by breathx** [comment]
@clearloop I've found some errors in our runtime builds, so I think this will resolve the issue. Could you please wait up to 2 days when I create PR with the fix, that might solve the issue?

**Comment by breathx** [comment]
> > @clearloop I've found some errors in our runtime builds, so I think this will resolve the issue. Could you please wait up to 2 days when I create PR with the fix, that might solve the issue?
> 
> sure, I'll update it to 0.24.0 next days anyway, but it is not caused by this, I will delay this

#1635 is a fix with explanation I mentioned above
