### ISSUE TITLE
Message type tag

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#1656]
Additional field to outgoing messages (not replies), that will allow interface and user space to make sense of the payload

**Comment by NikVolf** [comment]
Imagine in the program logic there is something like this:

```
if (condition) {
   send_message(userA, TypeA)
} else {
   send_message(userA, TypeB)
}
```

Then there is no way to figure out how to decode payload in the interface unless you know what condition was fired

**Comment by breathx** [comment]
Can be performed from the payload (e.g. first byte defines type of furthers)
