### ISSUE TITLE
Demos are not being rebuilt after changes in their deps

### ISSUE THREAD

**Issue by ark0f** [gear-tech/gear#1793]
### Problem

During development you may change `gstd`, `gcore`, etc so you need to rebuild affected demo WASM artifacts but it's not done because build script tracks only demo's source code

### Steps

1. Change behavior in `gstd`, `gcore`, etc
2. Run pallet test
3. You will see WASM of demo wasn't rebuilt

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by gshep** [comment]
relates to #772

**Comment by breathx** [comment]
Isn't this cargo issue?

**Comment by breathx** [comment]
Fixed at actual master
