### ISSUE TITLE
Program initial state and lifecycle

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#18]
Initially, program is instantiated in "uninitialized" state. Until it achieves "initialized" state, all messages to it should not be handled.

Program can achieve "initialized" state, once it replies to the initialization message with non-trap reply

**Comment by gshep** [comment]
- [ ] example program demonstrating usage of `gr::wait` in `init`
- [ ] `ProgramEnum { Uninitialized, Initialized }`
- [ ] `MessageEnum { Init, Next }`
- [ ] adjust `gtest` since `init` can go to the waiting list
- [ ] adjust node
