### ISSUE TITLE
BENCHMARKING: make test which checks that instructions costs are not too small

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#1818]
### Problem to Solve

Currently we calculate instructions costs using benchmarked weight `minus (saturating)` `i64const` weight for each parameter. This can theoretically leads to the situation where some instruction has very small or zero cost.

### Possible Solution

Make test which checks that all instructions have weights bigger than some eristic values.

**Comment by breathx** [comment]
Fixed #1896
