### ISSUE TITLE
Redesign `gstd`

### ISSUE THREAD

**Issue by ark0f** [gear-tech/gear#1829]
### Problem to Solve

`gstd` seems to need redesign with functions like `msg::send_delayed_from_reservation_and_wait_for_reply`

### Possible Solution

.

**Comment by shamilsan** [comment]
We could introduce many message types (all combinations):

```rust
struct MessageValue {
    payload: ...,
    value: ...,
}

struct MessageGasValue {
    message_value: MessageValue,
    gas: ...,
}

struct MessageGasValueDest {
    message_gas_value: MessageGasValue,
    dest: ...,
}
```

Also, we need to implement all combinations of methods to transit from one type to another.

```rust
impl MessageValue {
    pub fn gas(self, limit: u64) -> MessageGasValue {
       ...
    }
}
```

Finally, we are to implement send and reply functions for every type.

```rust
impl MessageGasValueDestDelayReservation {
    pub fn send(self) -> ... {
        msg::send_delayed_with_gas_from_reservation(...)
    }
}
```

We don't need to write all these types and implementations manually but use macros or code generation instead.

So sending a message yields a chain of function calls:

```rust
msg::payload("Hello!")
    .to(dest_id)
    .with_gas(1_000_000)
    .delayed(100)
    .from_reservation(rsv_id)
    .send()
    .expect("Unable to send");
```

### Pros

- Zero cost abstraction

### Cons

- Not so easy to implement
- Ugly source code and docs

**Comment by FrodoBaggins74524** [comment]
Use TryFrom -> https://doc.rust-lang.org/stable/std/convert/trait.TryFrom.html

**Comment by StackOverflowExcept1on** [comment]
The solution is located here: https://github.com/gear-foundation/gstd-fluent
