### ISSUE TITLE
subxt doesn't support `NonZero*` types

### ISSUE THREAD

**Issue by ark0f** [gear-tech/gear#1838]
### Problem

subxt doesn't support such types so we are limited in safety

### Steps

.

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by ark0f** [comment]
`subxt codegen` generates error when you changing corresponding field types to `NonZeroU64`:
```
The application panicked (crashed).
Message:  Unknown prelude type 'NonZeroU64'
Location: codegen/src/types/type_path.rs:130
```

**Comment by clearloop** [comment]
this is now supported https://github.com/paritytech/subxt/blob/v0.32.1/codegen/src/types/type_path.rs#L153 

ref #3392
