### ISSUE TITLE
Fix the frequency of cpu while benchmarking

### ISSUE THREAD

**Issue by MikitaS** [gear-tech/gear#1915]
### Problem to Solve

If benchmark is being running on CPU without limitations it may lead to bigger inaccuracies

### Possible Solution

make the frequency stable about 1-2 GHz

**Comment by ark0f** [comment]
Pretty good benchmark tips: https://llvm.org/docs/Benchmarking.html

Lowering CPU frequency to 1-2 GHz can be avoided by disabling frequency scaling (for example, set CPU governor mode to `performance` on Linux)
