### ISSUE TITLE
Gear libraries docs coverage

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#196]
- [x] `gstd`
- [x] `gcore`
- [x] `gmeta` 
- [x] `galloc`
- [x] `gtest`
- [x] `gclient`

**Comment by AndrePanin** [comment]
gcore documented in: https://github.com/gear-tech/gear/pull/387

**Comment by AndrePanin** [comment]
gstd documented in: https://github.com/gear-tech/gear/pull/555

**Comment by breathx** [comment]
This is still actual issue!

Updated description by adding `test` also.
