### ISSUE TITLE
Add more features to `gclient`

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#1962]
### Problem to Solve

`gclient` has some restrictions that bother using it for end-to-end tests. E.g., we don't have the possibility to get a sender account address or query program state.

### Possible Solution

- [x] Add public `account_id` or method to `GearApi`
- [x] Add `read_state` and `read_state_bytes` methods.
- [ ] Consider to replace `Borrow<AccountId32>` with `Into<AccountId32>` for convenience.
- [x] Consider to split [`get_from_mailbox`](https://docs.gear.rs/gclient/struct.GearApi.html#method.get_from_mailbox) into two methods: with `account_id` parameter and without it.
- [x] Consider adding an equivalent to the [gtest's `System::block_timestamp()`](https://docs.gear.rs/gtest/struct.System.html#method.block_timestamp) function.

**Comment by shamilsan** [comment]
Also, we can split [`get_from_mailbox`](https://docs.gear.rs/gclient/struct.GearApi.html#method.get_from_mailbox) into two methods: with `account_id` parameter and without it.

**Comment by fluiderson** [comment]
Consider to add an equivalent to the [gtest's `System::block_timestamp()`](https://docs.gear.rs/gtest/struct.System.html#method.block_timestamp) function.
