### ISSUE TITLE
Test no refund happens when a new sys-call is called except for `free` 

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#1998]
### Problem to Solve

We must be sure that when execution ends, global gas counters (gas/allowance) are the _freshest_ stores of gas info, not the gas in the `Ext`.

### Possible Solution

Tests should be done on real backends for all sys-calls. Would suggest to do it after some simplification refactoring between core-processor and backend levels.

**Comment by breathx** [comment]
After #2216 no refunds will be provided in free, so non actual

**Comment by breathx** [comment]
Furthermore, after #1247 refunds will be almost everywhere
