### ISSUE TITLE
Make checks that gas calculating for pages is cannot be overflowed.

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#2007]
### File Location(s)

[core-processor/src/executor.rs](https://github.com/gear-tech/gear/pull/1961/files/30ef669b1e617513cd29a57d7393da745819201f#diff-7db311ec2e461bbbe8116c485d313b390e787dd399ab081ee9a1840ed124535a)

### Proposal

-

**Comment by breathx** [comment]
Will be meaningless after #1894
