### ISSUE TITLE
Support aligned memory in wasmi

### ISSUE THREAD

**Issue by gshep** [gear-tech/gear#2012]
### Problem to Solve

wasmi for no_std environment uses common `Vec` for memory bytes buffer. To support lazy pages in such environments this need to be aligned on size of wasm memory page.

### Possible Solution

[stackoverflow/1758733](https://stackoverflow.com/a/69544158/1758733)

**Comment by breathx** [comment]
Similarly:
https://github.com/gear-tech/gear/issues/2011#issuecomment-1450406541
