### ISSUE TITLE
Add a possibility to save and restore program's memory pages in `gtest`/`gclient`

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2055]
### Problem to Solve

Sometimes it is helpful to have some not initial state of the program. E.g., you can perform some long during operation once and use its results in tests multiple times.

### Possible Solution

Add to `gtest`/`gclient`:

- Function for saving the whole program's memory to file: `save_memory(program_id, file_path)`
- Function for restoring the program's memory from a file: `restore_memory(program_id, file_path)`

Also: 

- Consider using a text format for the file to keep it in the version control system.
- Don't keep empty memory blocks.
- File format should be interchangeable between `gtest` and `gclient`.

**Comment by breathx** [comment]
> I'm not sure that #2331 completely solves this issue. The idea was, for example, to collect some state by running `gtest` (which is quicker), e.g., to add many accounts to a fungible-token program, then run the same program with saved state using `gclient`.
> 
> But need some comments from @LouiseMedova

Ohh, you're about this stuff. Makes sense as well, agree.
