### ISSUE TITLE
change `min_pages` type in `ImportedMemory` from `u32` to `WasmPageNumber`

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#2094]
### File Location(s)

pallets/gear/src/benchmarking/code.rs

**Comment by tltsutltsu** [comment]
It appears that the issue has been resolved now, so I am closing it.

pallets/gear/src/benchmarking/code.rs:
```rust
pub struct ImportedMemory {
    pub min_pages: WasmPage,
}
```
