### ISSUE TITLE
use `TrimmedString` for global names in `GlobalsCtx`

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#2098]
### File Location(s)

[core-backend/common/src/lazy_pages.rs](https://github.com/gear-tech/gear/pull/1988/files/55e7748b7428483d5594328b4ad0295e2b312d5f#diff-37fb51e19dec925a94d0609cc0723eabd2b3d8d7759aaad92e883ec2b786e63a)

### Proposal

__IMPORTANT__: need to implement `TryFrom` for `TrimmedString`, using `From` is RESTRICTED!!!!

**Comment by StackOverflowExcept1on** [comment]
Have we forgotten this place?
https://github.com/gear-tech/gear/blob/1b9618fb30c15457336ce583762a8f9b5ebd68ad/runtime-interface/src/lib.rs#L71-L78

**Comment by tltsutltsu** [comment]
Seems so. I'll fix it soon
