### ISSUE TITLE
Fix runtime upgrade and queue processing test on CI

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2146]
### Problem

`Test: Runtime upgrade and queue processing` runs infinitely (and is canceled by GitHub) on CI when pushing to master and (sometimes) when pushing to PR.

### Steps

1. https://github.com/gear-tech/gear/actions/runs/3999729777/jobs/6863986326
2. https://github.com/gear-tech/gear/actions/runs/4017119677/jobs/6901053887

### Possible Solution

Refactor the test

**Comment by breathx** [comment]
Test wasn't actual and no more required, was deleted
