### ISSUE TITLE
Optimize performance of the runtime-fuzzer

### ISSUE THREAD

**Issue by techraed** [gear-tech/gear#2189]
̶-̶ ̶[̶ ̶]̶ ̶W̶h̶e̶n̶ ̶f̶u̶z̶z̶e̶r̶ ̶r̶e̶c̶e̶i̶v̶e̶s̶ ̶p̶r̶o̶g̶r̶a̶m̶s̶,̶ ̶w̶h̶i̶c̶h̶ ̶h̶a̶v̶e̶ ̶r̶e̶c̶u̶r̶s̶i̶v̶e̶ ̶c̶a̶l̶l̶s̶ ̶o̶r̶ ̶b̶u̶s̶y̶ ̶l̶o̶o̶p̶s̶ ̶(̶w̶h̶i̶c̶h̶ ̶c̶o̶n̶s̶u̶m̶e̶ ̶a̶l̶l̶ ̶t̶h̶e̶ ̶g̶a̶s̶)̶ ̶i̶t̶ ̶w̶o̶r̶k̶s̶ ̶r̶e̶a̶l̶l̶y̶ ̶s̶l̶o̶w̶ ̶a̶l̶t̶h̶o̶u̶g̶h̶ ̶w̶h̶i̶l̶e̶ ̶b̶u̶i̶l̶d̶i̶n̶g̶ ̶t̶h̶e̶ ̶f̶u̶z̶z̶ ̶t̶a̶r̶g̶e̶t̶ ̶t̶h̶e̶ ̶`̶-̶C̶ ̶o̶p̶t̶-̶l̶e̶v̶e̶l̶=̶3̶`̶,̶ ̶b̶y̶ ̶d̶e̶f̶a̶u̶l̶t̶ ̶f̶u̶z̶z̶ ̶t̶a̶r̶g̶e̶t̶ ̶i̶s̶ ̶b̶u̶i̶l̶d̶ ̶w̶i̶t̶h̶ ̶`̶r̶e̶l̶e̶a̶s̶e̶`̶ ̶m̶o̶d̶e̶.̶ ̶I̶ ̶g̶u̶e̶s̶s̶ ̶w̶e̶ ̶c̶a̶n̶ ̶r̶e̶s̶e̶t̶ ̶s̶o̶m̶e̶ ̶f̶l̶a̶g̶s̶ ̶s̶e̶t̶ ̶b̶y̶ ̶t̶h̶e̶ ̶`̶c̶a̶r̶g̶o̶ ̶f̶u̶z̶z̶ ̶r̶u̶n̶`̶ ̶t̶o̶ ̶i̶n̶c̶r̶e̶a̶s̶e̶ ̶p̶e̶r̶f̶o̶r̶m̶a̶n̶c̶e̶,̶ ̶b̶u̶t̶ ̶i̶t̶ ̶r̶e̶q̶u̶i̶r̶e̶s̶ ̶s̶o̶m̶e̶ ̶a̶c̶c̶u̶r̶a̶c̶y̶ ̶i̶n̶ ̶o̶r̶d̶e̶r̶ ̶n̶o̶t̶ ̶t̶o̶ ̶l̶o̶o̶s̶e̶ ̶f̶u̶z̶z̶i̶n̶g̶ ̶q̶u̶a̶l̶i̶t̶y̶ ̶w̶i̶t̶h̶ ̶r̶e̶m̶o̶v̶i̶n̶g̶ ̶s̶o̶m̶e̶ ̶o̶f̶ ̶p̶a̶r̶a̶m̶s̶ ̶a̶n̶d̶ ̶f̶l̶a̶g̶s̶.̶   NOT ACTUAL, fuzzer is quite fast.
- [ ] Make fuzzer multithreaded. It seems to be easy with cargo-fuzz -> just use `-jobs` param, but possible negative consequences must be held.
- [ ] Consider introducing parallel fuzzing with common corpus directory (the other fuzzer should be AFL or any other).
- [x] It's recommended to avoid logging in the fuzz-target for a huge performance. I guess we can turn off logging and turn in it easily during crash investigation.
- [ ] Ease fuzzer job in docker by setting max total time param when running fuzzer (https://llvm.org/docs/LibFuzzer.html#options). We should check how many bytes are changed within corpus mutation process. If there are very few of them, then it seems irrelevant to run fuzzer for long time, as there will be quite a lot of similar test cases. Still we get benefit for fuzzer by the deepness of the coverage with the corpus.
- [ ] Use `merge=1` param when running fuzzer to minimize corpus
- [ ] Use corpuses with bytes, which were used by `node-loader` to generate such gear programs, execution of which resulted in  runtime panics 
- [ ] Use a wasms from our workspace as corpus for fuzzer

**Comment by SabaunT** [comment]
Don't hesitate to update the list

**Comment by SabaunT** [comment]
Logs are disabled when running fuzzer on production machine
