### ISSUE TITLE
Remove charging in gr_read for gr_size

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#2224]
### Problem

In ext::read we call "Self::size", which charges for "gr_size" syscall call. This is not correct and need to be removed. 
https://github.com/gear-tech/gear/blob/5f4512a0e72f4736e359806025b188d85349e8d2/core-processor/src/ext.rs#L639-L646

### Steps

-

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by breathx** [comment]
Included in #1846, also got partially solved by charging on backend side
