### ISSUE TITLE
fix costs for page data uploading, memory grow and static pages 

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#2226]
### File Location(s)

pallets/gear/src/schedule.rs

### Proposal

In MemoryWeights corresponding fields must be fixed. Maybe some benchmarked values must be set, maybe some heuristics.

**Comment by ByteNacked** [comment]
It seems this issue was already partially done. 
Only test `pallets/gear/src/tests.rs` `alloc_charge_error` remains to be fixed.
