### ISSUE TITLE
Segmentation fault due to Wasmer cache incompatibility between node versions

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2237]
### Problem

Sometimes the node crashes with the segmentation fault after the binary upgrade due to incompatibility of the Wasmer cache after changes in protocol.

### Steps

Occurs occasionally.

### Possible Solution

1. Clear the Wasmer cache before running the node.
2. Add versioning to the Wasmer cache.

**Comment by grishasobol** [comment]
Wee need to update wasmer to version 3.1 - there they fixed some bugs , may be this one also.

**Comment by grishasobol** [comment]
Also we have versioning in wasmer cache - for each wasmer version we make new directory for caches

**Comment by shamilsan** [comment]
> Also we have versioning in wasmer cache - for each wasmer version we make new directory for caches

As I see the problem is not in wasmer versions but in the incompatibilities between our versions.

**Comment by shamilsan** [comment]
Fixed in #2925
