### ISSUE TITLE
Deal with multiple rents (blocked by #1286)

### ISSUE THREAD

**Issue by MikitaS** [gear-tech/gear#2270]
we have an extra reservation of gas 'reserve_for' after message was sent to mailbox

name of test: delayed_send_user_message_with_reservation
file: pallets/gear/src/tests.rs

need to be examined why it's still reserved

**Comment by breathx** [comment]
That's not only about single `reserve_for`, it mostly affects cases when different rent apply on each other.
To solve this provide named locks for each node and use
```rust
if GasTree::lock(id).unwrap().is_zero() {
    GasTree::consume(id).unwrap()
}
```
instead of just consuming for branches of retrieving by some rent-relative stuff
