### ISSUE TITLE
Test the network with the batch of messages filling the whole block

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2300]
We need to write a script to see whether the network can process a batch of messages that fills the block in terms of weight.

- All programs should be different.
- Upload N programs with different code hashes.
- Send N messages (1 per program) to fill the whole block in terms of weight.

**Comment by breathx** [comment]
Still actual

**Comment by shamilsan** [comment]
> Still actual

Could you please add details about it to find more appropriate solution?

**Comment by shamilsan** [comment]
No additional info, closing.
