### ISSUE TITLE
`gcli` tests are not stable

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2322]
### Problem

1. `gcli::gear rpc::test_calculate_upload_gas` (https://github.com/gear-tech/gear/actions/runs/4296465067/jobs/7488219558)

<details><summary>Click to expand/collapse</summary>
<p>

thread 'rpc::test_calculate_upload_gas' panicked at 'called `Result::unwrap()` on an `Err` value: Subxt(Rpc(ClientError(Call(Custom(ErrorObject { code: ServerError(8000), message: "Runtime error", data: Some(RawValue("Application(Execution(AbortedDueToTrap(MessageWithBacktrace { message: \"host code panicked while being called by the runtime: range end index 122112 out of range for slice of length 102368\", backtrace: Some(Backtrace { backtrace_string: \"\\n    0: 0x186431 - <unknown>!sp_io::sandbox::extern_host_function_impls::instantiate::h1b0bbc9b5c51a258\\n    1: 0x9e3a2 - <unknown>!<sp_sandbox::host_executor::Instance<T> as sp_sandbox::SandboxInstance<T>>::new::hc185d61156da57b1\\n    2: 0x12eb5f - <unknown>!<gear_backend_sandbox::env::SandboxEnvironment<E,EP> as gear_backend_common::Environment<EP>>::new::h1b3201f7397aa7e6\\n    3: 0x116a48 - <unknown>!gear_core_processor::executor::execute_wasm::hb82dc8e91b794ebd\\n    4: 0xcd87b - <unknown>!gear_core_processor::processing::process::hfe6fa748485e5e1f\\n    5: 0x5bad0 - <unknown>!pallet_gear::pallet::Pallet<T>::calculate_gas_info::h45d4c3f47756286c\\n    6: 0x158d99 - <unknown>!GearApi_calculate_gas_info\\n\" }) })))")) })))))', gcli/tests/rpc/mod.rs:41:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

</p>
</details>

2. `gcli::gear cmd::reply::test_command_reply_works` (https://github.com/gear-tech/gear/actions/runs/4295740962/jobs/7486565695)

<details><summary>Click to expand/collapse</summary>
<p>

thread 'cmd::reply::test_command_reply_works' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', gcli/tests/cmd/reply.rs:31:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

</p>
</details>

### Steps

Occurs occasionally.

**Comment by gshep** [comment]
Yep, it is definitely relating to cache however it is no so easy to reproduce this one. I suspect that it is a race: every `rpc` test runs its own node process with the same program binary and all these processes use the same cache directory. Obviously I cannot reproduce it locally too =).

So one probable workaround is to run one test, for example `gcli::gear rpc::test_calculate_upload_gas` itself, before execution of all others. This trick should trigger correct program binary caching hence the others just read the data.

**Comment by gshep** [comment]
It's up to you

**Comment by shamilsan** [comment]
> what about closing this issue momentary again since the fails haven't happened again recently? @shamilsan

Agree.
