### ISSUE TITLE
gclient: Get all messages from the mailbox

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2325]
### Problem to Solve

E.g., we need to get a message from the mailbox that a program has sent. We need a message identifier, but we can't obtain it.

### Possible Solution

~Need to add a method to `EventProcessor` or `EventListener` that will process events and find the `UserMessageSent` event and return its details. It is similar to the `EventProcessor::reply_bytes_on` function but should capture arbitrary messages.~

Add a function to get all messages from the mailbox.

**Comment by breathx** [comment]
Which arbitrary messages do you mean? You can just query your mailbox and get all messages with their ids for the case, isn't it?

**Comment by SabaunT** [comment]
what about https://github.com/gear-tech/gear/blob/92416bd668584d1fd5f1b95b24d6a28bedbb07d0/gclient/src/api/storage/mod.rs#L48 ?

**Comment by shamilsan** [comment]
> what about
> 
> https://github.com/gear-tech/gear/blob/92416bd668584d1fd5f1b95b24d6a28bedbb07d0/gclient/src/api/storage/mod.rs#L48-L53

But where can we obtain `message_id` if it is just a message but not a reply to our message?

**Comment by breathx** [comment]
> > what about
> > https://github.com/gear-tech/gear/blob/92416bd668584d1fd5f1b95b24d6a28bedbb07d0/gclient/src/api/storage/mod.rs#L48-L53
> 
> But where can we obtain `message_id` if it is just a message but not a reply to our message?

Do you mean something like:
- send message that trigger some king of subscription in program logic
- subscribe for mailbox updates, collecting them to be able to process further
- once program send message, some logic from p.2 executed?

**Comment by shamilsan** [comment]
> Do you mean something like:
> 
>     * send message that trigger some king of subscription in program logic
> 
>     * subscribe for mailbox updates, collecting them to be able to process further
> 
>     * once program send message, some logic from p.2 executed?

Maybe we can just wait for the first message from the given program id?

@LouiseMedova what do you think about use cases?

**Comment by LouiseMedova** [comment]
I think in testing we just need to be able to get the necessary message from the mailbox:
- We can get it, by example, by indicating the sender's address;
- Or may be you can just just add the function that gives all the messages from mailbox and we can filter them by the sender's id and the payload.
