### ISSUE TITLE
Update licences and copyrights

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2339]
- [ ] Update copyright year to 2023 in all headers
- [ ] Make the preamble style the same through all crates (e.g., compare: https://github.com/gear-tech/gear/blob/master/HEADER-GPL3 and https://github.com/gear-tech/gear/blob/master/gcli/src/lib.rs)
- [ ] Change examples license to MIT (https://github.com/gear-tech/gear/tree/master/examples)
- [ ] Update Rust edition to `2021` when it is older.

**Comment by NikVolf** [comment]
writing this issue probably takes more time than actually updating it
