### ISSUE TITLE
gclient: `GearApiWithNode` doesn't support login operation

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2397]
### File Location(s)

gclient/src/api/mod.rs

### Proposal

`GearApiWithNode` can't provide `GearApi::with` method as it implements `Deref` that can use `&self` only instead of `self`.
Also, it is quite inconvenient to have two structures (`GearApiWithNode` and `GearApi`).

Consider to combine the node functionality in `GearApi`.

**Comment by DennisInSky** [comment]
@shamilsan I have taken a look at the current impl. What if we, as you suggested, just incorprate the `Node` struct as an `Option` inside the `GearApi` struct adn expose 2 functions: `GearApi::dev_from_path` and `GearApi::vara_from_path`

**Comment by shamilsan** [comment]
> @shamilsan I have taken a look at the current impl. What if we, as you suggested, just incorprate the `Node` struct as an `Option` inside the `GearApi` struct adn expose 2 functions: `GearApi::dev_from_path` and `GearApi::vara_from_path`

Good solution 👍
