### ISSUE TITLE
Add `cargo update` to `pre-commit` section of Makefile

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#2479]
### Problem to Solve

do the updating and fixing jobs oursevles as possible as we can to prevent the minor, verbose and endless PRs from @dependabot

### Possible Solution

add `cargo update`/`update` to this section https://github.com/gear-tech/gear/blob/62e602efcf5b207c0a7794f89177f71563236df1/Makefile#L7

**Comment by shamilsan** [comment]
This may yield in unrelated changes in PR (say fixes according to the new version of some crate).

We may set dependabot to trigger less frequently (e.g. weekly) and combine several PRs to the one manually. Not ideal but as an option.
