### ISSUE TITLE
Panic in lazy-pages signal handler

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2575]
### Problem

The node can't start on Linux machine.

Version: [`gear 0.1.4-5c685d0f15c`](https://github.com/gear-tech/gear/commit/5c685d0)

### Steps

1. Clean chain DB
2. Start the node
3. See the error

### Possible Solution

Check the panic in the source code: 

https://github.com/gear-tech/gear/blob/master/lazy-pages/src/sys/unix.rs#L107

### Relevant Log Output

![image](https://user-images.githubusercontent.com/66209982/233576613-5d0760a4-ed38-441b-86ae-5ea9e40d0e70.png)

![image](https://user-images.githubusercontent.com/66209982/233576674-313dc3bf-3427-4383-b7cb-d9fc2531bc0c.png)

**Comment by ukint-vs** [comment]
The cache is incompatible. We will find how to check and avoid this in the future. Perhaps we need to add a flag that validators can set and use with care. @grishasobol

**Comment by shamilsan** [comment]
It seems to have the same reason as #2237

**Comment by shamilsan** [comment]
Fixed in #2925.
