### ISSUE TITLE
Rename all generics in the `core-backend` so they emphasize their nature/purposes

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#2654]
### Proposal

For example, `EP` can be changed to `EntryPoint`, `PrepMem` to `MemoryPreparationError`, `T` in `Environment::execute` to `MemoryPreparationError`.

It's hard to navigate in the code with short unclear generics names.

**Comment by SabaunT** [comment]
This is a good first issue for newcomers.

**Comment by tltsutltsu** [comment]
I'll take it
