### ISSUE TITLE
Consider another error for `Ext::check_forbidden_destination`

### ISSUE THREAD

**Issue by techraed** [gear-tech/gear#2700]
### File Location(s)

https://github.com/gear-tech/gear/blob/8c82ff9554fd5c4db7574b80852ba83dc6636c0e/core-processor/src/ext.rs#L366

### Proposal

It must be something like `SyscallUsageError`, which we already have in errors crate. Better to Maybe there's a need to make it more complex error variant.

**Comment by SabaunT** [comment]
Need first to solve the problem with backwards compatibility.
