### ISSUE TITLE
Install gear-node, gcli via homebrew

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#2771]
### Problem to Solve

The expected behavior is 

```
$ brew tap gear-tech/homebrew
$ brew install gear
$ brew install gcli
```

ref https://github.com/gear-tech/gear/pull/2753#discussion_r1229410817

### Possible Solution

- [ ] Add a new formula in our org (and maintain the versions with CI ?), since we have short urls for the installation now, it could be easy to go
- [ ] PR to homebrew-core ( actually only for stable version imo bcz that could be hard to manage )

https://docs.brew.sh/Formula-Cookbook

**Comment by shamilsan** [comment]
Should we build and distribute `gcli` separately? Now it is included as a `gear` subcommand in nightly builds (https://get.gear.rs/#gear-nightly).

**Comment by shamilsan** [comment]
Let's add new issues to the dedicated repo.
