### ISSUE TITLE
Make code in gear-wasm-instrument more readable and try not to use magic numbers

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [gear-tech/gear#2826]
### File Location(s)

utils/wasm-instrument/src/lib.rs

### Proposal

Create functions like `push_global`, `export_global`, `push_import` etc. Count inserted imports with some mutable variable instead of doing it via magic numbers.

**Comment by breathx** [comment]
Im I correct, that as magic numbers you mean insertion of our gas counting?
