### ISSUE TITLE
Merge the function tree of sandbox and wasmi

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#2837]
### Problem to Solve

After https://github.com/gear-tech/gear/pull/2682 and https://github.com/gear-tech/gear/pull/2721 we have cleaned a lot of duplicated code in core-sandbox, but there are still potential to make the code cleaner and more simple

### Possible Solution

support conditional compilation in`core-backend/codegen` for sandbox and wasmi, wrap them into [function-like-procedural-macros](https://doc.rust-lang.org/reference/procedural-macros.html#function-like-procedural-macros), accept function list and generate different function trees, the expected code in `core-backend/sandbox/src/env.rs`

```rust
use gear_backend_codegen::func_tree;
use gear_backend_common::FUNC_TREE;

pub(crate) fn build<Ext>(
    ...
) {
  let funcs = func_tree!(FUNC_TREE);

  ...
}
```

**Comment by ark0f** [comment]
Consider to deprecate because of #2992

**Comment by clearloop** [comment]
> Consider to deprecate because of #2992

make sense
