### ISSUE TITLE
Fix the benchmark workflow

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#2868]
### Problem

dsherret/rust-toolchain-file@v1 doesn't work for the benchmarks workflow but the CI workflow

https://github.com/gear-tech/gear/actions/runs/5380011067/jobs/9762069362

https://github.com/gear-tech/gear/actions/runs/5380108788/jobs/9762320067

### Steps

1.
2.
3.

**Comment by StackOverflowExcept1on** [comment]
I hope it will be merged soon: https://github.com/dsherret/rust-toolchain-file/pull/1
