### ISSUE TITLE
Consider generating weights to sepcified branch triggered by issue_comment

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#2873]
### Problem to Solve

it could be useful to generate weights to specified branch with comment, for example, 

=> I just created a PR, and need to generate the weights to my branch
=> I comment my PR 「/generate-weights」
=> the workflow starts to generating weights for my branch and make a commit to it

### Possible Solution

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment

**Comment by StackOverflowExcept1on** [comment]
`issue_comment` can create a lot of skipped jobs in the "actions" tab. we can try to use https://probot.github.io
