### ISSUE TITLE
Tune benchmarking for non-return sys-calls

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#2938]
### Problem to Solve

For some sys-calls we use very unstable benchmarks.
https://github.com/gear-tech/gear/blob/df995d23c0fd807d63b553ac9cb9891b3eaeae3a/pallets/gear/src/benchmarking/mod.rs#L1471-L1479

We must found a way to increase accuracy here.

### Possible Solution

Make benchmark weight for empty execution. Do new execution for each new sys-call calling and then subtract empty execution weight from execution with sys-call calling weight.

**Comment by gshep** [comment]
The idea there is to split all syscalls benchmarks into two sets. The first one is the set with pretty stable syscalls. The second one should include benchmarks for one-time-call syscalls (`gr_wait, gr_exit, gr_reply*, etc). Apply for this very set of benchmarks parameters like `repetitions = 1_000`, `step = 2`. Repetition count should be determined to provide thorough benchmark accuracy.
