### ISSUE TITLE
Pallets refactoring after M1 review

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2949]
### Proposal

- [ ] Some pallet refactoring can be done (e.g. too long functions in airdrop pallet).
- [ ] Add benchmarking for `transfer_vested`.
- [ ] Cover more tests for negative scenarios (e.g. `NotVesting`, `ScheduleIndexOutOfBounds`).

**Comment by ukint-vs** [comment]
> too long functions in airdrop pallet

Can you explain?

**Comment by shamilsan** [comment]
> Can you explain?

I've checked functions in https://github.com/gear-tech/gear/blob/master/pallets/airdrop/src/lib.rs

You are right, and they don't look too long 😄 

Maybe it was about other traits? We need to review some of them.
