### ISSUE TITLE
Consider to restructure the directory tree

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#297]
Consider making the top-level directory structure simpler. For example:

`.github`

<details open=""><summary><code>core</code></summary>
<p>

```
├── backend
├── runner
└── src
```
</p>
</details>

`examples`

<details open=""><summary><code>gstd</code></summary>
<p>

```
├── async
├── galloc
├── gcore
└── src
```
</p>
</details>

<details open=""><summary><code>node</code></summary>
<p>

```
├── common
├── pallets
│   └── gear
├── runtime
├── rti
└── src
```
</p>
</details>

<details open=""><summary><code>scripts</code></summary>
<p>

```
├── ansible
└── docker
```
</p>
</details>

<details open=""><summary><code>tests</code></summary>
<p>

```
├── btree
├── common
├── distributor
├── node
└── rpc
```
</p>
</details>

<details open=""><summary><code>utils</code></summary>
<p>

```
├── gear-test-cli
├── gtest
└── wasm-proc 
```
</p>
</details>

**Comment by breathx** [comment]
I don't actually think that we need this now. First of all, many things changed and dir tree is not the same that was before. Secondly, we are still on active developing stage and everything with our current crates structure may change. Closing for now, but would like to open same considering issue just before crates.io listing and proper versioning.
