### ISSUE TITLE
Make doc tests in gear libraries compilable

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#298]
We will add examples to the `gstd` in-code documentation. We need to implement dummy syscalls in `std` mode for making these examples compilable as doc tests. We can add a dummy crate and use it as dev-dependency in `gstd`.

**Comment by breathx** [comment]
Actual for `gcore` and `gtest` also

**Comment by shamilsan** [comment]
All doc-tests are compilable now and added to CI (#1963).
