### ISSUE TITLE
Add imported host functions to the wasm linker only

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#2991]
### Problem to Solve

in the current code, we are adding all functions to the env of the linker for each execution

sandbox: https://github.com/gear-tech/gear/blob/master/core-backend/sandbox/src/env.rs#L208
wasmi: https://github.com/gear-tech/gear/blob/master/core-backend/wasmi/src/funcs_tree.rs#L92

which is not necessary and have risk of performance ( but it could be insufficient )

---

It could be necessary when we are reusing the linker, but in the current implementation of `core-processor`, we are creating template instances

https://github.com/gear-tech/gear/blob/master/core-processor/src/executor.rs#L252

### Possible Solution

iterate the imports of specified module and import functions on-demand

**Comment by gshep** [comment]
not necessary since only required funcs added - https://github.com/gear-tech/gear/blob/master/sandbox/host/src/sandbox/wasmer_backend.rs#L251
