### ISSUE TITLE
Re-think config of allowed values for params in `wasm-gen`

### ISSUE THREAD

**Issue by techraed** [gear-tech/gear#3092]
### Problem to Solve

Ranges of values, that can be used for sys-calls params (`ParamType`) must be valid, closer to real wasm executions.

### Possible Solution

This is related to #3091, but focuses more on range of values used as params for sys-calls to be valid/closer to reality. These values for sys-call params can make the sys-call execution result in an error, but that mustn't be very frequent.

**Comment by SabaunT** [comment]
Closed in favour of #3293

**Comment by techraed** [comment]
Actually not worth being a separate task
