### ISSUE TITLE
Proposal: introduce gr_break

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#3216]
### Problem to Solve

Currently we have 8 non-return syscalls:
```
gr_panic(payload: *const BufferStart, len: Length)
gr_oom_panic()
gr_exit(inheritor_id: *const Hash)
gr_leave()
gr_wait_for(duration: BlockNumber)
gr_wait_up_to(duration: BlockNumber)
gr_wait()
gr_out_of_gas()
```

Aslo we need one more sys-call `gr_stack_overflow` for stack limit exceeded (currently simple unreachable is using). Unfortunately instruction `unreachable` has no literal argument, so we cannot use it to identify the reason of unreachable execution. 

So, the problem is that for each one new special exit from execution reason we need to make separate sys-call, which cause problems in support, code size, code complexity and etc. 

### Possible Solution

Make two sys-calls instead:
```
gr_user_break(data: u64) -> !;
gr_system_break(data: u64) -> !;
```

`gr_user_break` is instead of all user available sys-calls. `data` contains next information:
1) `data.to_le_bytes[0]` - contains code of sys-call functionality. Should it act like gr_panic, gr_leave, gr_exit and etc.
2) `data.to_le_bytes[1]` - contains custom user information code. For some sys-calls it can be useful. For example: instead of panic with some panic string program can panic with some code and send this code in system reply.
3) in bytes `data.to_le_bytes[2..8]` special sys-call data is encoded (not scale codec). For example for `gr_wait_for` is `BlockNumber`. For `gr_panic` `data.to_le_bytes[2..6]` is  `*const BufferStart` and `data.to_le_bytes[6..8]` is `Length` (65536 bytes for panic payload should be enough)

`gr_system_break` is instead of `gr_out_of_gas` and `gr_stack_overflow`. Argument `data` just identifies whether it's `out_of_gas` or  `stack_overflow` occur.

### Notes

The signatures of this sys-calls can be expanded for more flexibility. For example:
```
gr_user_break(code: u64, data: u64) -> !;
gr_system_break(code: u64, data: u64) -> !;
```

gr_system_break will be restricted at instrumentation in original user code

**Comment by breathx** [comment]
Solved in #3512
