### ISSUE TITLE
Create a Script to Retrieve the Default Node Secret Key

### ISSUE THREAD

**Issue by EugenWay** [gear-tech/gear#3311]
### Problem to Solve

We need script for gear noders.
This script is designed to locate the gear-node path and extract the secret key for exporting into your wallet.

### Possible Solution

Navigate to the gear-node directory: cd gear-node/chains/vara/keystore
keep in minde secret key in ED25519 format, which is not compatible with most wallets.
For greater compatibility with wallets, consider providing the secret key as a seed phrase."

**Comment by shamilsan** [comment]
1. Script (or utility as we will write it in Rust) can be run from any location
2. The excellent starting point for the key is https://wiki.gear-tech.io/docs/node/backup-restore

For example, the node key on macOS for Staging V7 is in $HOME/Library/Application Support/gear/chains/gear_staging_testnet_v7/network/secret_ed25519

3. We are to check several paths and show only keys found. Firstly, old binaries had the name gear-node, so we must also check this path (macOS: `$HOME/Library/Application Support/gear-node`). Secondly, we had upgraded the network, so we are to check all versions (see history of this line: https://github.com/gear-tech/gear/blob/master/node/service/src/chain_spec/gear.rs#L147): `staging_testnet`, `staging_testnet_v2`, `staging_testnet_v3`, ... , `staging_testnet_v7`. 

4. Creating this directory: Run the gear binary without params.

```bash
❯ gear
2023-09-21 18:42:02 Gear Node
2023-09-21 18:42:02 ✌️  version 1.0.0-9eea531dae1
2023-09-21 18:42:02 ❤️  by Gear Technologies, 2021-2023
2023-09-21 18:42:02 📋 Chain specification: Gear Staging Testnet V7
2023-09-21 18:42:02 🏷  Node name: pink-caption-3526
2023-09-21 18:42:02 👤 Role: FULL
2023-09-21 18:42:02 💾 Database: RocksDb at /Users/shamil/Library/Application Support/gear/chains/gear_staging_testnet_v7/db/full
```

See the Database path and find the secret key.

```bash
❯ hexdump "/Users/shamil/Library/Application Support/gear/chains/gear_staging_testnet_v7/network/secret_ed25519"
0000000 48f0 7f6a 73f7 0a90 2af2 c601 8337 082b
0000010 c2cc 878e 115c f959 87c4 4731 519e 37f2
0000020
```

5. No need to deal with the wallet; just find the secret key, convert it to the seed phrase, and show it to the user. Remember to show the Network ID (e.g., `staging_testnet_v7`). Ideally, it would be to show the public key and P2P ID (e.g., `12D3KooWQNkJu7avkpZBFVoAZy38acTDNDSr18ATahaHkut8pJxH`), but let's keep it as the next stage after the first task has been done.
