### ISSUE TITLE
Fix comparison table percents

### ISSUE THREAD

**Issue by breathx** [gear-tech/gear#3346]
### Problem

https://github.com/gear-tech/gear/pull/3319#issuecomment-1731378626

gr_wait_up_to | 12.2 µs | 167.1 µs | -92.68% **<- this isn't 92%**

**Comment by StackOverflowExcept1on** [comment]
What's wrong? It shows a positive or negative percentage difference compared to the master branch.

name | master | tuned | diff
-- | -- | -- | --
gr_reply_commit | 20.8 µs | 16.7 µs | +24.61%
| gr_wait_up_to                           | 12.2 µs  | 167.1 µs                                                     | -92.68% |

```
16.7 + 24.61% = 20.80987
167.1 - 92.68% = 12.23172
```

The original formula was proposed by Grigory S.
https://github.com/gear-tech/gear/pull/2688#discussion_r1226368160

**Comment by breathx** [comment]
> What's wrong? It shows a positive or negative percentage difference compared to the master branch. You should interpret this as "performance degraded by 92% compared to master".
> 
> name	master	tuned	diff
> gr_reply_commit	20.8 µs	16.7 µs	+24.61%
> gr_wait_up_to	12.2 µs	167.1 µs	-92.68%
> ```
> 16.7 + 24.61% = 20.80987
> 167.1 - 92.68% = 12.23172
> ```
> 
> The original formula was proposed by Grigory S. [#2688 (comment)](https://github.com/gear-tech/gear/pull/2688#discussion_r1226368160)

Ohh, I see now. But seems that the formula isn't correct enough.
Cause we compare from the different side

**Comment by tltsutltsu** [comment]
Yeah, comparison seems "side reverted"

**Comment by breathx** [comment]
> Yeah, now it is hard to read and at first glance seems like sides were inverted.
> 
> For me this formula looks a lot more readable:
> 
> name	master	tuned	diff
> gr_wait_up_to	12.2 µs	167.1 µs	+1269.7%
> example	37.8 µs	40 µs	+5.82%
> another example	89.2 µs	62.2 µs	-30.72%

The only thing: I'd change sign of diff to make it showing "performance", -1269.7% in perf means that we become that much slower, +30.72% means that we increased our perf for that amount of percents

**Comment by StackOverflowExcept1on** [comment]
Closed in #3430
