### ISSUE TITLE
Don't transfer gas on `gr_wake`

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#335]
We don't need to transfer gas on `gr_wake`.

A process that wakes actually takes gas from a different user (original initiator) and should return unused gas to that one.

**Comment by NikVolf** [comment]
Interesting enough, sometimes it should be transferred

- In mutex scenario, it SHOULD NOT (because wake occurs by different message chain)
- In waiting for message reply, it SHOULD (because wake occurs in the same message chain)

So I guess it should be optional

**Comment by NikVolf** [comment]
Closed as more complex issue #336
