### ISSUE TITLE
Lower amount of traps when `Control` instructions are off for wasms from `wasm-gen`

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#3382]
### Proposal

If you turn off `Control` instructions from `wasm-gen`, the execution will become really fast, but the rate of `Traps` (`Possibly 'unreachable' instruction occurred`) becomes too high. There are basically 2 main reasons (wasmi): `out of bounds memory access` and `integer divide by zero`. The task is to lower the rate of these erros.

**Comment by StackOverflowExcept1on** [comment]
~1/2 of unreachables comes from `free` syscall: 
https://github.com/gear-tech/gear/blob/5b931e25403d62a1231c117c63baeed533972147/core-backend/src/funcs.rs#L330-L340
