### ISSUE TITLE
refactor(wasm-gen): introduce new approach for `PointerWriteDataGenerator`

### ISSUE THREAD

**Issue by mertwole** [gear-tech/gear#3398]
### File Location(s)

`utils/wasm-gen/src/config/syscalls/pointer_write.rs`

### Proposal

Compute offsets based on ones from `gsys` type definitions instead of providing it manually. For example, if we set `PointerWriteDataGenerator` to write `Value` and have `HashWithValue` then it will set offset to `size_of::<Hash>()`

**Comment by SabaunT** [comment]
Already done in the mentioned PR
