### ISSUE TITLE
Remove false positive clippy lint on next rust update

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [gear-tech/gear#3452]
### File Location(s)

`examples/constructor/src/builder.rs`
`scripts/src/clippy.sh`
rust-lang/rust-clippy#11545

### Proposal

```rust
    // TODO #3452: remove this on next rust update
    #[allow(clippy::useless_conversion)]
    pub fn add_from_iter(mut self, calls: impl Iterator<Item = Call>) -> Self { ... }
```

**Comment by SabaunT** [comment]
That clippy bug is fixed in commits to rust from 21-st September, but the bug with `overflow evaluating the requirement` (see https://github.com/rust-lang/rust/issues/117211) is from commits to rust from 19th September. That's why in #3451 we have to just skip it.
