### ISSUE TITLE
gtest: incorrect timestamp increment when using `System::spend_blocks`

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#3514]
### Problem

Block duration seems to be `1000` msecs:

https://github.com/gear-tech/gear/blob/master/gtest/src/system.rs#L177

### Steps

1. Try to use `System::spend_blocks`.
2. Check how block timestamp shanges.

### Possible Solution

Use constants for block duration.

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by breathx** [comment]
It was faster to implement fix than describe the issue
