### ISSUE TITLE
RPC-tests: should be reworked and reenabled.

### ISSUE THREAD

**Issue by ukint-vs** [gear-tech/gear#353]
RPC-tests should use `gear-js` using debug-mode in node.
Ideally, they should cover the functionality that exists in the `gtest`.

**Comment by shamilsan** [comment]
Maybe should we rename them to `js-tests` or `onchain-tests` to be more relevant?

**Comment by ukint-vs** [comment]
> Maybe should we rename them to `js-tests` or `onchain-tests` to be more relevant?

I think we should leave the name of the protocol used for testing, but how it is done is not important.
RPC already implies that testing takes place from external sources.
