### ISSUE TITLE
Fuzzer coverage doesn't work on current rust toolchain

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#3533]
### Problem

The common coverage generation workflow doesn't work and returns `error: Failed to load coverage: 'target/x86_64-unknown-linux-gnu/coverage/x86_64-unknown-linux-gnu/release/main': Malformed coverage data` when running `cargo cov -- show` on generated by `cargo-fuzz` artifacts. However, when we had `2023-04-25` rust version, everything was fine.

### Possible solution

Downgrade rust version

**Comment by StackOverflowExcept1on** [comment]
https://github.com/rust-lang/rust/issues/117788#issuecomment-1806730397
