### ISSUE TITLE
Log the internal panic messages in gtest

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#3544]
### Problem to Solve

ref #3520

log the panic messages written in program 

https://github.com/gear-tech/gear/issues/3520#issuecomment-1827395687

### Possible Solution

capture the message when `RunResult::reply_code` is `Some(Error(Execution(UserspacePanic)))`

**Comment by shamilsan** [comment]
We print the panic message as a debug log entry (https://github.com/gear-tech/gear/pull/3045). Or I am misunderstanding your task?

**Comment by clearloop** [comment]
oh I mean this https://github.com/gear-tech/gear/issues/3520#issuecomment-1827395687

**Comment by clearloop** [comment]
seems this is logged as well 

https://github.com/gear-tech/gear/blob/master/gtest/src/manager.rs#L746

**Comment by clearloop** [comment]
in favor of #3546
