### ISSUE TITLE
Access globals with runtime interfaces in lazy-pages

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#3547]
### Problem to Solve

ref #3017 

### Possible Solution

`gear_sandbox` is now hosting a store in thread level https://github.com/gear-tech/gear/blob/master/runtime-interface/src/gear_sandbox/detail.rs#L53, however, lazy-pages uses pointer to access the mutable wasm instances https://github.com/gear-tech/gear/blob/master/lazy-pages/src/globals.rs#L113

since we already can access the store with runtime interfaces, why not doing it in lazy-pages as well but not using pointers

### Notes

cc @ark0f @gshep

**Comment by gshep** [comment]
Could you elaborate a bit how would it help to avoid double mutable references to globals?
