### ISSUE TITLE
Add a possibility to cancel delayed messages

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#3562]
### Problem to Solve

Sometimes we need to have a possibility to cancel delayed messages that have not yet been sent.

## Use case

For example, we have a game with multiple players, each player interacts with the game through a dedicated program. The player can make a move within some timeout. If the player doesn't make a move, his move is automatic.

We can implement it with delayed messages (default move) that can be overridden with the action message sending (player's move). But if the player made a move, there is no need to send and process a delayed message.

### Possible Solution

Add an API to `gstd` that allows canceling a delayed message by its message ID.

```rust
use gstd::msg;

const DELAY: u32 = 20;

let msg_id = msg::send_delayed(dest, "Hello", 0, DELAY).expect("Unable to send");
// ...
msg::cancel_delayed(msg_id).expect("Unable to cancel");
```

**Comment by NikVolf** [comment]
Not sure this is required at all (introduce compexity in protocol for no big reason)

**Comment by NikVolf** [comment]
Not required
