### ISSUE TITLE
`gear-wasm-builder` v1.1.0: Stable clippy warns about unused import

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#3696]
### Problem

When trying to run the stable clippy against a program being built with `gear-wasm-builder` v1.1.0 from crates.io, we get an error:

```
error: unused import: `orig_project::*`
   --> src/lib.rs:1:20
    |
  1 | #![no_std] pub use orig_project::*;
    |                    ^^^^^^^^^^^^^^^
    |
    = note: `-D unused-imports` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unused_imports)]`

  error: could not compile `sharded-fungible-token-logic-wasm` (lib) due to previous error
  error: cargo command run failed: exit status: 101
Error: command exited with non-zero code `cargo clippy --all-targets --no-deps -- -Dwarnings`: 101
```

https://github.com/gear-foundation/dapps/actions/runs/7613159810/job/20732405845

### Steps

1. Set the latest stable Rust toolchain as default and remove any `rust-toolchain.toml` from the program directory.
2. Run `cargo clippy`
3. Check warnings.

### Possible Solution

Add `#[allow]` in generated crate or find the cause of the problem.

**Comment by StackOverflowExcept1on** [comment]
The CI in the dapps repository seems too strict. We previously had the same problems with warnings in `gear-wasm-builder` due to settings in `.cargo/config.toml`.
