### ISSUE TITLE
`gtest` v1.1.0: Can't compile tests on Linux

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#3697]
### Problem

When using `gtest` v1.1.0 from crates.io in the project, it is unable to build tests on Linux due to incompatible dependencies in deps tree (especially `wasmtime`). Moving to `gtest` from `gear` repo with `v1.1.0` tag helps.

https://github.com/gear-foundation/dapps/actions/runs/7637058675/job/20805177232

### Steps

1. Add `gtest = "1.1.0"` to dev-dependencies in the program's crate.
2. Run `cargo build` on Linux.
3. Get a linking error.

### Possible Solution

Reupload the `gtest` library to crates.io with a fixed dependencies versions.

**Comment by StackOverflowExcept1on** [comment]
Maybe we just forgot to replace `sp-core` with `gp-core`? It seems the problem is with `gclient` and `gsdk`, but not with `gtest`
https://github.com/gear-tech/gear/blob/9a37ccb406de68af8ddc6c851faa0c90ba0f0918/utils/crates-io/src/handler.rs#L222-L225

**Comment by clearloop** [comment]
just tested https://github.com/gear-foundation/dapps/tree/update-deps with modifying `gtest` to the crates-io version on my linux machine, it works ))

```
Linux opt 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
nightly-2023-09-05-x86_64-unknown-linux-gnu (default)
```

the problem on https://github.com/gear-foundation/dapps/pull/208 could be caused by cache, plz clean the cache in CI and retry

**Comment by gshep** [comment]
I was able to reproduce it on fresh Linux-box. Actually the issue is in the `core-processor` crate from crates.io since it produces the following deps-tree:
```

│   │   │   │   │   │   │   └── wasmtime v6.0.2
│   │   │   │   │   │   ├── gp-wasm-interface v7.0.1
│   │   │   │   │   ├── gp-runtime-interface v7.0.5
│   │   │   │   ├── gear-runtime-interface v1.1.0
│   │   │   ├── gear-sandbox v1.1.0
│   │   ├── gear-core-backend v1.1.0
│   ├── core-processor v1.1.0



│   │   │   │   │   │   │   │   │   └── wasmtime v8.0.1
│   │   │   │   │   │   │   │   ├── sp-wasm-interface v14.0.0
│   │   │   │   │   │   │   ├── sp-runtime-interface v17.0.0
│   │   │   │   │   │   ├── sp-core v21.0.0
│   │   │   │   │   ├── sp-io v23.0.0
│   │   │   │   ├── gear-runtime-interface v1.1.0
│   │   │   ├── gear-sandbox v1.1.0
│   │   ├── gear-core-backend v1.1.0
│   ├── core-processor v1.1.0


│   │   │   │   │   │   │   │   │   └── wasmtime v1.0.2
│   │   │   │   │   │   │   │   ├── sp-wasm-interface v8.0.0
│   │   │   │   │   │   │   ├── sp-runtime-interface v8.0.0
│   │   │   │   │   │   ├── sp-core v8.0.0
│   │   │   │   │   ├── sp-api v4.0.0
│   │   │   │   ├── frame-support v4.0.0
│   │   │   ├── gear-common v1.1.0
│   │   ├── gear-lazy-pages-interface v1.1.0
│   ├── core-processor v1.1.0
```
