### ISSUE TITLE
`gtest`: Reservations aren't removed after using

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#3699]
### Problem

When testing reservations using `gtest`, we can't exceed reservation limit (`256`) even if reservations are used.

### Steps

See the test: https://github.com/gear-tech/gear/pull/3698

### Possible Solution

Check `gtest::ExtManager::reserve_gas` / `unreserve_gas` / `update_gas_reservation` for completeness.

**Comment by techraed** [comment]
closed with https://github.com/gear-tech/gear/pull/4089
