### ISSUE TITLE
Enable staking interfaces for programs

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#3740]
### Problem to Solve

Lacking of DEX and stable coins, the scenarios of programs ( almost in all of the new chains, near, aptos, etc ) are limited in the ideas of smart contracts in Ethereum but without the financial background of Ethereum

Since we are running with POS system, unlocking the staking features of programs could also be a feature of our ecosystem, without DEX or stablecoins, for example, blast can be just with a staking feature "native yield"

The most popular dApps built with the staking features recently:

- https://www.eigenlayer.xyz/
  - this could be expanded to a super big dApp for polkadot as well once we have integration with it
- https://pooltogether.com/
  - vrf running with our programs will be really neat

### Possible Solution

same as `pallet-gear`, passing the staking calls to program

**Comment by gshep** [comment]
if I understand correctly it reminds of staking builtin actor first implemented in #3504. The builtin framework is currently being under refactoring in #3624 however we are waiting for the subsequent PR with the new implementation of staking broker on top of the framework.

**Comment by clearloop** [comment]
This have already been resolved
