### ISSUE TITLE
`msg::send_delayed` can be executed with low gas

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [gear-tech/gear#3744]
### Problem

https://github.com/gear-foundation/nft-marketplace/blob/934d47bf845875cb4891ab5ea4f730dc4a8a492f/ai-nft/src/lib.rs#L59-L68
for example you have contract that makes refund if the external provider does not respond to the request, but instead of panicking with "Error in sending delayed message" nothing happens when the user has not sent enough gas

### Steps

1. use this code
2. mint nft with low gas (0.03 TVARA)
3. wait ~250 blocks and make sure that the funds are not returned

### Possible Solution

return error when `send_delayed` can't be paid

**Comment by breathx** [comment]
Misuse of calculate_gas RPC call and/or program business logic error.
Explained personally. Shortly, send_delayed as syscall invocater gives guarantees to SEND message in case of returning OK, but has no guarantees for further execution of the message, following general design of the system/protocol.
