### ISSUE TITLE
Database-mapped memory pages

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#379]
When loading program to handle one message, it is suboptimal to load all memory pages. Instead, they should be all empty initially and access guard (mprotect) should be put, and they should load from db only once accessed.

**Comment by NikVolf** [comment]
After #381

**Comment by grishasobol** [comment]
As I can see https://github.com/WebAssembly/design/blob/main/FutureFeatures.md mprotect pages may be available only in the future. May be we can get page hash before run and after run, then compare them for each pages and store only that which is changed.
