### ISSUE TITLE
gclient and gsdk does not compile on the nightly version

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [gear-tech/gear#3915]
### Problem

see details #3899
https://github.com/gear-tech/gear/pull/3905/commits/7dd5e8ec4360cd190f5b84931f622a898c0012c6 should be reverted

### Steps

use latest gclient from crates io with our rust toolchain (in our workspace it works)

**Comment by clearloop** [comment]
resolved by https://github.com/gear-tech/gear/issues/3899 ? @StackOverflowExcept1on

**Comment by StackOverflowExcept1on** [comment]
@clearloop probably not resolved
