### ISSUE TITLE
Remove dependency to staking from builtin pallet

### ISSUE THREAD

**Issue by breathx** [gear-tech/gear#4048]
can we somehow avoid depending on staking pallet explicitly? if yes, place todo here pls

_Originally posted by @breathx in https://github.com/gear-tech/gear/pull/3843#discussion_r1667715493_
            
            
It requires just implementing isolated struct Actor<T: pallet_staking::Config> and replace calls to staking with pallet_staking::Pallet::<T>::call etc

**Comment by ekovalev** [comment]
Solved in that same PR #3843

**Comment by ekovalev** [comment]
Solved in that same PR https://github.com/gear-tech/gear/pull/3843
