### ISSUE TITLE
Set proper DB costs for `gtest`

### ISSUE THREAD

**Issue by breathx** [gear-tech/gear#4052]
### Problem

#3962 must've made gtest as real as node testing, but gas consumption still not even close to be accurate due to incorrect db weights

### Steps

fix it here:
https://github.com/gear-tech/gear/blob/1fdd1e07ab3a0028a96785eac76b02d978709470/gtest/src/lib.rs#L489

**Comment by techraed** [comment]
Fixed in #4216
