### ISSUE TITLE
Add a unified result processor after program executing

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#494]
### Proposal

At the moment we process the running results in three locations in a similar fashion—pallet-gear, gear-test, and standalone tests.
- [ ] Need to add a trait for accessing to key-value storage for making an abstraction above chain/in-memory storage.
- [ ] Need to implement either trait functions with higher-level storage access (e.g. message queue, waitlist, program storage, etc.) or a separate struct.
- [ ] Need to implement the trait for both on-chain and in-memory storage.

**Comment by NikVolf** [comment]
in some sense was implemented in #502, in some sense not needed anymore after that
