### ISSUE TITLE
Use RPC calls to compute expected gas spends for "init"/"handle" message sending 

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#541]
### File Location(s)

https://github.com/gear-tech/gear/blob/master/pallets/gear/src/tests.rs

### Proposal

Need to improve our `get_gas_spent` RPC call to make pallet tests more neat. Possible pros:
1. Can compute expected spends for sending init message by any user. For now we just use one user address and compute expected spends for init message by looking into actual block gas consumption after running the block. 
2. Expected spends for "init"/"handle" message can be computed accurately. For now tests can compute "potential" spends using gas limit values. Also compute "more accurate" expected spends by looking to block gas usage value. That's clumsy, but works.

**Comment by SabaunT** [comment]
Do after #502 is merged

**Comment by breathx** [comment]
Closes with #587
