### ISSUE TITLE
Can i implement smart contracts in C++ or Python?

### ISSUE THREAD

**Issue by DoubleDi** [gear-tech/gear#594]
In the readme it is stated, that 
```
Gear provides the easiest and most cost-effective way
to run WebAssembly programs (smart-contracts) compiled from
many popular languages, such as Rust, C/C++ and more.
```

How to actually do that? 
I did not find any c++ library analog, like gstd or gcore?

I understand that gear uses WASM, so basically I can use any language, that can be compiled to WASM. 
But how do I use the blockchain API internally without a C++ library, with primitives like ActorId and msg?

**Comment by NikVolf** [comment]
C++ it is possible, but we yet to provide standard library for it

happy to sponsor this development btw

**Comment by breathx** [comment]
Answered
