### ISSUE TITLE
Introduce critical sections for atomic operations

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#614]
### Problem to Solve

Some critical sections may be interrupted by a trap. e.g. due to insufficient gas limit. For example:

```rust
static mut FROM_BALANCE: i32 = 1000;
static mut TO_BALANCE: i32 = 0;

fn transfer() {
    if FROM_BALANCE >= 1000 {
        FROM_BALANCE -= 1000;
        // --> Possible trap here
        TO_BALANCE += 1000;
    }
}
```

In the case of a trap, this results in losing the balance.

### Possible Solution

Need to have some tools to implement atomic operations.

**Comment by NikVolf** [comment]
We've decided to go with https://github.com/gear-tech/gear/issues/108

which will make this unneeded
