### ISSUE TITLE
Need proper handling for messages with limbro prog destination

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#629]
Programs are being added to the program storage in extrinsics. That means, that if initialization failed, program still exists in the storage, but with uninitalized state. There is a use case when in the message queue there are init and handle messages to the same destination. If init message fails, the handle message (in the current version) goes to wait list, which is wrong.

Suggestion: the dispatch message should be consumed without any execution, instead of dispatch message should be created a reply message for the original dispatch message source. Discussion around that was made during the dev-team sync call.

**Comment by gshep** [comment]
perhaps relates to #507

**Comment by SabaunT** [comment]
> perhaps relates to #507

exactly
