### ISSUE TITLE
Merge `waiting_init_prefix` into `ProgramState::Uninitialized`

### ISSUE THREAD

**Issue by gshep** [gear-tech/gear#630]
### File Location(s)

`gear/common/lib.rs`

### Proposal

@breathx  suggested on the previous status call.

Remove `waiting_init_prefix` & etc. Store all such messages in `ProgramState::Uninitialized` and adjust code to the change.

**Comment by breathx** [comment]
This will be closed as a part of moving programs to separate pallet in order of #578 resolving

**Comment by breathx** [comment]
Found the issue where this one appears as duplicate: #788. Closing
