### ISSUE TITLE
In-memory tokenomic management 

### ISSUE THREAD

**Issue by breathx** [gear-tech/gear#649]
### Problem to Solve

At the moment `gear-test`, `gtest`, and real on-chain behavior is different due to absence of some core features. So the test-cases that are success in tests may fail in real conditions.

### Possible Solution

Need to bring `ValueTree` and rent charging into in-memory testing.

Not sure, that concrete this issue should cover unification of tests and real behavior, but it's in our closest _to do ..._ Minimal for now is to create detached in-memory implementations.

**Comment by NikVolf** [comment]
avoid creating complex issue that has no design what so ever
