### ISSUE TITLE
Lighten `gear-test` compilation

### ISSUE THREAD

**Issue by breathx** [gear-tech/gear#650]
### File Location(s)

`gear/gear-test`

### Proposal

Our `gear-test` native environment execution, meant as base and light-weight, not like that and compiles a lot.

Remove unused dependencies.

- [ ] For `check_main()` change argument `ext: Option<Box<dyn Fn() -> sp_io::TestExternalities + Send + Sync + 'static>>` for something like this `Option<impl Fn(impl Fn() -> ()) -> ()>`, by pre-building `Externalities`, which run the given closure inside.
- [ ] Remove support for ss58 ids, because our ecosystem don't use this tool anymore, and such kind of ids is superfluous for internal core testing.

**Comment by ark0f** [comment]
Do we actually need `Externalities` option if they are not used anywhere?

**Comment by breathx** [comment]
> Do we actually need `Externalities` option if they are not used anywhere?

Aren't they?
https://github.com/gear-tech/gear/blob/9fd91a056c61c023cda6a0073753beffbff1bc6b/gear-test/src/check.rs#L644

**Comment by ark0f** [comment]
This line is from `check_main` function, which is used only with `None` argument in 1 place along the whole code base

**Comment by breathx** [comment]
> This line is from `check_main` function, which is used only with `None` argument in 1 place along the whole code base

Ah, you're right. We had node runtests option before. It's replaced now with runtime cli tests. Seems there is no reason to keep that argument now.
