### ISSUE TITLE
Extrinsics `resume_program` and program destruction

### ISSUE THREAD

**Issue by gshep** [gear-tech/gear#652]
### Problem to Solve

Allow users to stop the execution of a program but keep its ID and hash of the state. So program goes to the temporary storage and takes less space on-chain.

Second feature is to restore program from such kind of storage. Caller has to provide memory-pages (state) and enough value to continue program execution.

### Possible Solution

API in `common` crate + tests. On node side there will be two extrinsics using this API.

### Notes

after #453

**Comment by NikVolf** [comment]
Transaction needed only for "resume"

Programs got destroyed automatically when they have no resources to continue operating and restored by someone who provide resources
