### ISSUE TITLE
Wasm-builder compilation sticking 

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#772]
### Problem

When galloc is changed wasm-builder may take old allocator to compile test.

### Steps

1. go to branch gsobol-wasm-builder-compile-sticking
2. run `$ cargo test --package pallet-gear --lib -- tests::resume_program_works --exact`
3. It must fail, else clean wasm builder and try again: `$ cargo clean -p gear-wasm-builder`
4. Add "checks" feature for dlmalloc in galloc/Cargo.toml, with this feature test resume_program_works must goes right
5. If test is failed, then tries to clean wasm builder and try again

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
<Paste your log here>
```

</p>
</details>

**Comment by shamilsan** [comment]
After some investigation. `cargo` seems to not trigger to rebuild `tests-init-wait` after changing features in `galloc/Cargo.toml`. I am not sure it is possible to fix in `gear-wasm-builder`.

**Comment by breathx** [comment]
This is the known cargo issue about feature-dependent compilation from pre-built binaries.
So I think we need to close the issue and migrate from cargo to cargo hack extension to minimise issue appearance in future.
