### ISSUE TITLE
Move `common::Program` & corresponding entities to gear-program pallet

### ISSUE THREAD

**Issue by gshep** [gear-tech/gear#788]
### Proposal

This is a first step of #578

**Comment by breathx** [comment]
Will be not actual after merging common and core structs (Program, Message, etc)

**Comment by breathx** [comment]
> Will be not actual after merging common and core structs (Program, Message, etc)

Almost done in #769

**Comment by SabaunT** [comment]
Will be nice to move program storage to `pallet-gear-program` as well.
