### ISSUE TITLE
check-spec.sh incorrectly checks

### ISSUE THREAD

**Issue by ark0f** [gear-tech/gear#822]
### Problem

![](https://user-images.githubusercontent.com/21154701/162039622-bfb74d24-7a5c-49af-b6b0-1a7ab8dfbb57.png)

`check-spec.sh` compares differences between your branch and `origin/master` (e.g. `master` in https://github.com/gear-tech/gear for core devs). So, like on the image, when `core` or `runtime-interface` are changed the script will tell you to bump the version

### Steps

1. checkout new branch
2. wait until commits are added with changes in crates like `core` or `runtime-interface` in master branch
3. run `check-spec.sh` and you will be required to bump version

### Notes

You can avoid such bug if you pull the master to your branch before running the script

**Comment by breathx** [comment]
Do you have any possible solution for that?

**Comment by shamilsan** [comment]
I'd not spend time on it if there is no simple solution. Keeping the branch synced with the master seems to be not quite difficult or boring.
