### ISSUE TITLE
Remove `Clone` for wasmtime `Ext`

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#852]
Sandbox back-end doesn't have any external data clones, which gives some safety guarantees. Will be nice to have the same for wasmtime back-end. This also opens a path to remove `Rc<RefCell>>` from ext carriers and use reference types which give safety guarantees during compile time. The latter can be implemented in the same PR.

**Comment by ark0f** [comment]
I guess we can leave `ReplicableExtCarrier` for wasmtime backend only and remove other carriers for the rest at least

**Comment by SabaunT** [comment]
Not relevant with changes here #853.
