### ISSUE TITLE
Computationally prove dispatche queue processing will take place

### ISSUE THREAD

**Issue by SabaunT** [gear-tech/gear#893]
Some works on removing constant time limits of executing extrinsics and processing dispatches in the queue (i.e., time for `on_idle`) are planned. We need to make tests that prove an ability to process dispatches in the queue in any case of extrinsics load, when there are no constant time limits

**Comment by SabaunT** [comment]
Will be implemented, If only decide to implement #913

**Comment by breathx** [comment]
That wasn't fully motivated initially, but will be totally unused once #1531 solved
