### ISSUE TITLE
update default gas fee values for wasm pages init/load/grow 

### ISSUE THREAD

**Issue by grishasobol** [gear-tech/gear#895]
### Problem to Solve

After benchmarks instructions price tune, price for wasm pages is too low, so we must to tune it also.

### Possible Solution

Make benchmarks for core processor work

**Comment by grishasobol** [comment]
See file: [core-processor/src/configs.rs](https://github.com/gear-tech/gear/pull/882/files/435cf8900c40d8e1a5b186a51974937c3118e7d5#diff-f6d89e9834d25043e83dd5d621902d26985f0bbe925c987a6660b70910ef4bdc)

**Comment by shamilsan** [comment]
What's the progress? @ukint-vs

**Comment by breathx** [comment]
> What's the progress? @ukint-vs

Here may not be any progress at all. It's more about just to consider how much we should pay. No benchmarks *for memory usage* may be provided atm 

Also some time ago it was set equal to db read-writes it does
