### ISSUE TITLE
WASM targets coverage

### ISSUE THREAD

**Issue by ark0f** [gear-tech/gear#910]
### Problem to Solve

We don't have code coverage for WASM targets at the moment because `wasm32-unknown-unknown` target doesn't have `profiler_builtins` crate required for coverage instrumentation (I doubt it will do ever)

### Possible Solution

Extract `profiler_builtins` crate from Rust sources, modify it for WASM specifity and then integrate it (sysroot, cargo patch feature, etc)

### Notes

https://github.com/Amanieu/minicov is very close to that

cargo patch feature doesn't allow to patch such sysroot crates

**Comment by shamilsan** [comment]
I don't see a reason to cover Wasm examples, as their purpose is only to test the core code.
