### ISSUE TITLE
Make a separate implementation of `Ext` for production and test environments.

### ISSUE THREAD

**Issue by ukint-vs** [gear-tech/gear#921]
### Proposal

We have `LazyPagesExt` which is a wrapper around the default `Ext` implementation that overrides some functions, this is a dirty trick that shows us that we must implement the `Ext` directly in the modules in which we have the execution of programs. We can define a separate `Ext` for the test environments (gear-test, gtest) and for the pallet so that programs can directly access runtime environment (storage, configs, costs) without passing things like `BlockInfo`, gas counters etc. For example, right now we can't just implement the `is_program` syscall which needs access to the storage which can change state while the program is running, so `Ext` must have access to all environment from the top.

**Comment by breathx** [comment]
Partially got solved, other things will be done in lazy pages refactoring
