### ISSUE TITLE
Optimize wasm without using third party tools.

### ISSUE THREAD

**Issue by ukint-vs** [gear-tech/gear#922]
### Proposal

Need to find a way to optimize artefacts in `wasm-builder` without using `wasm-opt`.

**Comment by clearloop** [comment]
we can strip custom sections like carg-contract does https://github.com/paritytech/cargo-contract/blob/62cf21f6811261b0c382acd4b84b4d903e14823b/src/cmd/build.rs#L487

**Comment by ark0f** [comment]
What motivation?

**Comment by shamilsan** [comment]
> What motivation?

To not force to install additional dependencies I guess.

**Comment by breathx** [comment]
> > What motivation?
> 
> To not force to install additional dependencies I guess.

Exactly. Somehow wrap optimisation logic inside gear wasm builder to prevent forcing `binaryen` manual installation

**Comment by breathx** [comment]
> we can strip custom sections ( keep `name_section` for debugging ) like carg-contract does https://github.com/paritytech/cargo-contract/blob/62cf21f6811261b0c382acd4b84b4d903e14823b/src/cmd/build.rs#L487

Good catch. Feel free to apply this or open issue on it
