### ISSUE TITLE
Refactor the algo of getting the gas spent in `get_gas_spent`

### ISSUE THREAD

**Issue by clearloop** [gear-tech/gear#977]
### File Location(s)

https://github.com/gear-tech/gear/blob/9bd56a0aa17931985c80ec3fa2377518eacc25bb/pallets/gear/src/lib.rs#L576

### Proposal

We can just get the max gas spent via `JournalNote::GasBurned { amount, .. }`

in case of fixing the node key issue in https://github.com/gear-tech/gear/pull/975, we can not get `remaining_gas` via `T::GasHandler::get_limit(message_id)` after the message has been consumed ( in some cases it would be `None` )

**Comment by breathx** [comment]
> We can just calculate the gas spent via adding up JournalNote::GasBurned { amount, .. }

It was like that before, but it's not right way.

Imagine, you have contract, which burns N of gas and sends M to another program(-s).
Your proposal says that we need apply N gas for success execution, but in fact, it's (N + M)

**Comment by breathx** [comment]
> We can not get remaining_gas via T::GasHandler::get_limit(message_id) after the message has been consumed ( in some cases it would be None )

Can't we get it before consume? catch `MessageConsumed` note, query limit and process note afterward

**Comment by clearloop** [comment]
> > We can not get remaining_gas via T::GasHandler::get_limit(message_id) after the message has been consumed ( in some cases it would be None )
> 
> Can't we get it before consume? catch `MessageConsumed` note, query limit and process note afterward

Yeah, I think the capture of https://github.com/gear-tech/gear/blob/9bd56a0aa17931985c80ec3fa2377518eacc25bb/pallets/gear/src/lib.rs#L567 is in a wroing place in current implementation, it shoud be inside of https://github.com/gear-tech/gear/blob/9bd56a0aa17931985c80ec3fa2377518eacc25bb/pallets/gear/src/lib.rs#L580,

**Comment by clearloop** [comment]
> > We can not get remaining_gas via T::GasHandler::get_limit(message_id) after the message has been consumed ( in some cases it would be None )
> 
> Can't we get it before consume? catch `MessageConsumed` note, query limit and process note afterward

```rust
for note in journal {
    let remaining_gas = T::GasHandler::get_limit(root_message_id)
        .map_err(|_| {
            b"Internal error: unable to get gas limit after execution".to_vec()
        })?
        .ok_or_else(|| {
            b"Internal error: unable to get gas limit after execution".to_vec()
        })?;

    match note {
        JournalNote::SendDispatch { .. }
        | JournalNote::WaitDispatch(..)
            | JournalNote::MessageConsumed(..) => {
                let gas_spent = initial_gas.saturating_sub(remaining_gas);
                if gas_spent > max_gas_spent {
                    max_gas_spent = gas_spent;
                }                                                                                                                                                                                                                                                   
            }
        JournalNote::MessageDispatched(CoreDispatchOutcome::MessageTrap {
            trap,
            ..
        }) => {
            return Err(format!(
                "Program terminated with a trap: {}",
                trap.unwrap_or_else(|| "No reason".to_string())
            )
                       .into_bytes());
        }
        JournalNote::GasBurned { message_id, amount } => {
            if message_id == MessageId::from_origin(root_message_id) {
                log::debug!("gas spent {:?}", amount);
            }
        }
        _ => (),
    }

    core_processor::handle_journal(vec![note], &mut ext_manager);
}
```

I think this is what exactly we need

**Comment by SabaunT** [comment]
> > We can just calculate the gas spent via adding up JournalNote::GasBurned { amount, .. }
> 
> It was like that before, but it's not right way.
> 
> Imagine, you have contract, which burns N of gas and sends M to another program(-s). Your proposal says that we need apply N gas for success execution, but in fact, it's (N + M)

The function runs loop, which will process messages with M gas. Isn't it enough to just catch `GasBurned` note after executing each message?

**Comment by breathx** [comment]
> > > We can just calculate the gas spent via adding up JournalNote::GasBurned { amount, .. }
> > 
> > 
> > It was like that before, but it's not right way.
> > Imagine, you have contract, which burns N of gas and sends M to another program(-s). Your proposal says that we need apply N gas for success execution, but in fact, it's (N + M)
> 
> The function runs loop, which will process messages with M gas. Isn't it enough to just catch `GasBurned` note after executing each message?

Nope, cause this will not mention gas sent, which is important for applying

**Comment by breathx** [comment]
> > > We can not get remaining_gas via T::GasHandler::get_limit(message_id) after the message has been consumed ( in some cases it would be None )
> > 
> > 
> > Can't we get it before consume? catch `MessageConsumed` note, query limit and process note afterward
> 
> ```rust
> for note in journal {
>     let remaining_gas = T::GasHandler::get_limit(root_message_id)
>         .map_err(|_| {
>             b"Internal error: unable to get gas limit after execution".to_vec()
>         })?
>         .ok_or_else(|| {
>             b"Internal error: unable to get gas limit after execution".to_vec()
>         })?;
> 
>     match note {
>         JournalNote::SendDispatch { .. }
>         | JournalNote::WaitDispatch(..)
>         | JournalNote::MessageConsumed(..) => {
>             let gas_spent = initial_gas.saturating_sub(remaining_gas);
>             if gas_spent > max_gas_spent {
>                 max_gas_spent = gas_spent;
>             }                                                                                                                                                                                                                                                   
>         }
>         JournalNote::MessageDispatched(CoreDispatchOutcome::MessageTrap {
>             trap,
>             ..
>         }) => {
>             return Err(format!(
>                 "Program terminated with a trap: {}",
>                 trap.unwrap_or_else(|| "No reason".to_string())
>             )
>                        .into_bytes());
>         }
>         _ => (),
>     }
> 
>     core_processor::handle_journal(vec![note], &mut ext_manager);
> }
> ```
> 
> I think this mb what exactly we need, just typo in the current implementation, also, mb we can only process `JournalNote::SendDispatch`, `JournalNote::WaitDispatch(..)`, `JournalNote::MessageConsumed(..)` to calculate the gas spent?
> 
> One last confusion: is `max_gas_spent` exactly what we want in `get_gas_spent`? or we need to add up each of the gas spent?

Experimentally we found the most suitable solution for calculating:
We take as fact, that everything will be payed from the initial gas (external gas node) - and we store the maximum diff of initial gas and current amount left on each iteration, because our platform has ability to return unused gas back and so on. So the biggest deviation is the right amount of gas to apply for successful execution

**Comment by breathx** [comment]
The way where we should handle journal after manual note handling seems right
