### ISSUE TITLE
Consider other options for performance benchmarks

### ISSUE THREAD

**Issue by gshep** [gear-tech/gear#986]
### Proposal

Caused by #900 

The following options can be considered as a further evolvement of the task:
1. choose some algorithm as a base measurement of hardware state. Run it on the main branch and the source PR branch then use the results to adjust benchmark values;
1. use box-plots for both the main branch and the feature/working branch. Since collecting statistics is a time consuming operation we could create some label and perform the operation only for labeled PRs;
1. add new standalone runner. All performance benchmarks analysis should be done on the runner only.

**Comment by breathx** [comment]
Solved by master builds with weights
